### PR TITLE
Enable syntax highlighting for emacs

### PR DESCRIPTION
**Pull request by casey**
Adds a local variable block in the justfile to enable syntax highlighting under emacs.

PS This is a sweet project! I started doing [something similar](https://github.com/casey/boilerplate), but yours has many more features. Feel free to cannibalize anything you want from mine. It think the only things that yours is missing that mine has is a simple `.travis.yml`, as well as a bunch of convenience recipes.

### CODE REVIEW

**Comment by ssokolow** [comment]
I welcome the emacs syntax highlight, but could you either use the single-line syntax which Python 2.x uses for character coding overrides (`# -*- coding: utf-8 -*-
`) or move it above the Vim modeline? (Or both, ideally, since Vim doesn't have a multi-line version, so "emacs above Vim" would be the least footgunny way to end the file.)

Vim only looks within a certain number of lines of the beginning and end of the file (5 by default) and I'd rather not have Vim break unexpectedly some day because someone enhanced the Emacs settings and it grew longer than 4 lines.

Also, thanks for giving me the opportunity to remember that I wanted to add an [`.editorconfig` file](http://editorconfig.org/) to communicate my `rustfmt` settings to editors in a portable manner.

**Comment by casey** [comment]
From [this page](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html), it seems that emacs only recognizes the single line form on the first line of a file.

It recognizes the multi-line form as long as it is within 3000 characters of the end of the file, so it should be safe to use that, and put it above the vim modeline. (Stranger things have happened, but it seems unlikely that the vim modeline would balloon to more than 3000 characters.)

**Comment by ssokolow** [comment]
Thanks. Merged. :)

**Comment by ssokolow** [comment]
> Feel free to cannibalize anything you want from mine.

I've borrowed your `.travis.yml` and written my own `CONTRIBUTING.md` inspired by yours. The justfile, brev, and comparing your and my tweaks to `main.rs` will have to wait until I can spare more time.

**Comment by ssokolow** [comment]
Oh, and I did notice one other difference between our approaches. You have a `CUSTOMIZING.md` while I've been very careful to limit my "how to start a new project" list to...

```
cargo new --template rust-cli-boilerplate fooproject
cd fooproject
rm README.md
```

...to make it as effortless as possible. (That's why I phrased my new `CONTRIBUTING.md` the way I did.)

**Comment by casey** [comment]
That's pretty nice, I didn't know that cargo allowed specifying a template like that.

**Comment by ssokolow** [comment]
The feature has been [a long time coming](https://github.com/rust-lang/cargo/issues/396), but got merged into nightly [on February 1st](https://github.com/rust-lang/cargo/pull/3004) and I'm now just waiting for it to ride its way down to stable channel so I don't have to futz around with `rustup run nightly ...`.

**Pull request merged**
